server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=dbo
    username: sa
    password: 123456
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc:
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.firstdemo.pojo

logging:
  level:
    com.example.firstdemo.mapper: debug

